image: node:18

pipelines:
    default:
        - step:
              name: Build and Test
              caches:
                  - node
              script:
                  - npm install
                  - npm run production
